name: bookshelf
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  xml: ^6.5.0
  html: ^0.15.5+1
  mockito: ^5.4.5
  get_it: ^8.0.3
  palette_generator: ^0.3.3+6
  file_picker: ^10.1.2
  path: ^1.9.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - test/assets/test_image.png
    - test/assets/test_url_image.png